#APP SPECIFIC CUSTOM PROPERTIES
app:
  kafka:
    consumer:
      topic: my_topic

#SPRING PROPERTIES
spring:
#  main:
#    web-application-type: none
  kafka:
    schema-registry-url: http://localhost:8081
    bootstrap-servers: "localhost:9092"
    properties:
      schema.registry.url: http://localhost:8081
      specific.avro.reader: true
    consumer:
      group-id: my_group_v4
      auto-offset-reset: earliest
      key-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
